execute pathogen#infect()
execute pathogen#helptags()

filetype plugin indent on
syntax on

set relativenumber number
set clipboard=unnamed

" Colors
set background=dark
colorscheme solarized
" colorscheme elflord

