execute pathogen#infect()
execute pathogen#helptags()

filetype plugin indent on
syntax on

set relativenumber number

" Colors
set background=dark
colorscheme solarized
" colorscheme elflord

let g:pymode_python = 'python3'

